% Prints out steady-state statistics

convergence_report(adjtype,finegrid,MMiter,sizeofMMgrid,pDIFF,piter,VDIFF,Viter,PdistDIFF,Pdistiter); 
disp(sprintf('\n'))  
disp(sprintf('Elapsed time is %d seconds',round(toc)))
% disp(sprintf('\n'))  
% disp(sprintf('Inflation decomposition check : %0.3g percentage points off',decompCheck))     
% disp(sprintf('Wage calculation check        : %0.3g%% off',wageCheck))     
disp(sprintf('\n'))
disp(sprintf('Consumption                   : %0.3g',Cbar)) 
disp(sprintf('Hours                         : %0.3g',Nbar))
disp(sprintf('Real money balances           : %0.3g',Avgmoney))
disp(sprintf('Price level                   : %0.3g',pbar))
disp(sprintf('Wage level                    : %0.3g',wbar))
disp(sprintf('Utility level                 : %0.4g',U))
disp(sprintf('\n'))
disp(sprintf('Quarterly inflation           : %0.3g%%',100*inflation))     
disp(sprintf('Frequency of price changes    : %0.3g%%',100*freqpchanges))
disp(sprintf('Mean price change             : %0.3g',100*EPchange))     
disp(sprintf('\n'))
disp(sprintf('Mean absolute price change    : %0.3g',100*MeanAbsPchange))
disp(sprintf('Median absolute price change  : %0.3g',100*MedAbsPchange))
disp(sprintf('\n'))
disp(sprintf('Mean price increase           : %0.3g',100*EPincrease))
disp(sprintf('Median price increase         : %0.3g',100*MedPincrease))
%disp(sprintf('Std of price increases        : %0.3g',100*STDpincrease))
disp(sprintf('\n'))
disp(sprintf('Mean price decrease           : %0.3g',-100*EPDecrease))
disp(sprintf('Median price decrease         : %0.3g',-100*MedPdecrease))
disp(sprintf('\n'))
disp(sprintf('Std of price changes          : %0.3g',100*STDpchange))  
disp(sprintf('Kurtosis of price changes     : %0.3g',KurtosisPchange))                                           
disp(sprintf('\n'))
disp(sprintf('Fraction of price increases   : %0.3g%%',100-100*fracPriceDecr))
disp(sprintf('Fraction of price changes <5%% : %0.3g%%',100*fracSmallChanges))
if adjtype==3                                                        
disp(sprintf('\n'))
disp(sprintf('Menu cost as %% of revenue    : %0.3g%%',McostinRev))
disp(sprintf('Menu cost as %% of wage bill  : %0.3g%%',McostinWageBill))
disp(sprintf('Menu cost as %% of consumption: %0.3g%%',McostinCbar))
end
disp(sprintf('\n'))
disp(sprintf('Mean abs distance from p*     : %0.3g%',100*AvAbsDistFromPstar))
disp(sprintf('Median abs distance from p*   : %0.3g%',100*MedAbsPdistans))
disp(sprintf('\n'))
disp(sprintf('Mean D as %% of median V       : %0.3g%%',100*AverD/MedV))
disp(sprintf('Median D as %% of median V     : %0.3g%%',100*MedD/MedV))
disp(sprintf('Std of D as %% of median V     : %0.3g%%',100*StdD/MedV))
disp(sprintf('\n'))
disp(sprintf('State dependence metric [0 1] : %0.3g',CalvoMenuMetric))

